name: ebook_tutorial_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4

  # Google Sign-In (충돌 방지 위해 iOS 전용 추가)
  google_sign_in: ^6.2.1
  #google_sign_in_ios: ^5.9.0

  # Apple Sign-In
  #sign_in_with_apple: ^7.0.1

  # 기본 아이콘
  cupertino_icons: ^1.0.6

  # 상태 관리
  provider: ^6.1.2

  # 로딩 애니메이션 (선택)
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
