name: ebook_tutorial_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4

  # Google Sign-In (iOS 전용 플러그인 삭제, 하나만 남깁니다)
  google_sign_in: ^6.2.1

  # Apple Sign-In (일단 나중에 연결)
  # sign_in_with_apple: ^7.0.1

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
