// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA46egnJnT7-rBT1u_eTX94bHoxJ3QL-DA',
    appId: '1:574290558433:web:7e71682472b7b5c50066a0',
    messagingSenderId: '574290558433',
    projectId: 'ebook-ai-62c35',
    authDomain: 'ebook-ai-62c35.firebaseapp.com',
    storageBucket: 'ebook-ai-62c35.firebasestorage.app',
    measurementId: 'G-K3M2FDS4EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxfeAdx323-Hv84HNZVw2y-HlSY08ycmk',
    appId: '1:574290558433:android:d24c4fdb073d24bd0066a0',
    messagingSenderId: '574290558433',
    projectId: 'ebook-ai-62c35',
    storageBucket: 'ebook-ai-62c35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQT-zaPcxVdggWPI8rlUWEZmvvyFynuhY',
    appId: '1:574290558433:ios:c7b7877bcc9707390066a0',
    messagingSenderId: '574290558433',
    projectId: 'ebook-ai-62c35',
    storageBucket: 'ebook-ai-62c35.firebasestorage.app',
    iosBundleId: 'com.example.ebookTutorialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQT-zaPcxVdggWPI8rlUWEZmvvyFynuhY',
    appId: '1:574290558433:ios:c7b7877bcc9707390066a0',
    messagingSenderId: '574290558433',
    projectId: 'ebook-ai-62c35',
    storageBucket: 'ebook-ai-62c35.firebasestorage.app',
    iosBundleId: 'com.example.ebookTutorialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA46egnJnT7-rBT1u_eTX94bHoxJ3QL-DA',
    appId: '1:574290558433:web:19990e6e62e8168c0066a0',
    messagingSenderId: '574290558433',
    projectId: 'ebook-ai-62c35',
    authDomain: 'ebook-ai-62c35.firebaseapp.com',
    storageBucket: 'ebook-ai-62c35.firebasestorage.app',
    measurementId: 'G-GEPFJ7KK8X',
  );
}
